---
kind: pkgfile.Build
spec:
  targets:
    - sbc-raspberrypi
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: PKGS
        defaultValue: v1.8.0-alpha.0-34-gce49757
---
kind: common.Build
spec:
    ignoredPaths:
      - go.work.sum
